services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8182:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8282:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/RTT
      - SESSION_SECRET=kasomhelst
      - CLIENT_URL=https://group2.sustainability.it.ntnu.no
      - GOOGLE_CLIENT_SECRET=123123
      - GOOGLE_CLIENT_ID=123132
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:5
    container_name: mongo
    expose:
      - "27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge