services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8182:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8282:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27028/RTT
      - SESSION_SECRET=kasomhelst
      - CLIENT_URL=http://localhost:5173
      - GOOGLE_CLIENT_SECRET=123123
      - GOOGLE_CLIENT_ID=123132
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27028:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: