services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8182:80"
    depends_on:
      - backend

  backend:
    image: node:16
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8282:5000"
    command: ["npm", "run", "start"]
    environment:
      - MONGO_URI=mongodb://localhost:27017/RTT
      - SESSION_SECRET=kasomhelst
      - CLIENT_URL=http://localhost:5173
      - GOOGLE_CLIENT_SECRET=123123
      - GOOGLE_CLIENT_ID=123132
      - PORT=3000
      
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-local-debug:/data/db


secrets:
  mongo_admin_pwd:
    file: ./secrets.folder/mongo_admin_pwd.txt

networks:
  some-fancy-network:

volumes:
  mongo-local-debug: